apiVersion: v1
baseDomain: example.com
metadata:
  name: my-cluster
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
platform:
  aws:
    region: us-east-1
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
